# Generated by Django 5.0.6 on 2024-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='info',
            field=models.TextField(verbose_name='info'),
        ),
    ]
