# Generated by Django 5.0.6 on 2024-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AddField(
            model_name='about',
            name='icono',
            field=models.CharField(default='none', max_length=50, verbose_name='Icono'),
        ),
    ]
